### ISSUE TITLE
Can't load the IDEAS package to OMEdit 

### ISSUE THREAD

**Issue by tatigabd** [open-ideas/IDEAS#669] opened 2017-02-09 10:21 UTC
Hi! Could someone help me please to open this IDEAS package in OpenModelica Editor? When I am trying to open the file IDEAS/package.mo, I am getting some syntax, grammar and scripting error messages, such as following (please, see an attached file). I've just start working with this language and OMEdit, and I am so sorry for these stupid questions but I can't solve them by myself.
[IDEAS&OMEdit.txt](https://github.com/open-ideas/IDEAS/files/763321/IDEAS.OMEdit.txt)

**Comment by Mathadon** [comment] 2017-02-09 15:35
Hi, I'll try to look at it during the coming week. Feel free to remind me in case I forget!

**Comment by Mathadon** [comment] 2017-02-12 23:48
The problem is that OpenModelica only supports 32 bit integers, which makes sense since many machines used to have 32 bit processors.
However, we use an integer to represent 'absolute' time in the `CalendarTime` model. This is a number in seconds since 1970, which is about 1.5e9 - too large to put into an integer.
I suppose we should be able to change this by using a float instead. I'll need to look into this further.

**Comment by tatigabd** [comment] 2017-02-13 11:24
Hi, thanks in advance for your help. Thank you for the advices, I've just installed the 62-bit Modelica on a computer with 62-bit operating system, and those errors with numbers are gone but the similar one left [1](see a picture here https://yadi.sk/i/PkWPEmrt3Dzv6p). Also as you can see another 2 errors left on this step which I can't solve.

**Comment by Mathadon** [comment] 2017-02-13 17:52
That's stuff we need to sort out, which shouldn't be too much work. I'll have a look at it once I get openmodelica running again on my pc.

Btw, you can drag pictures straight into the gitlab text box.

**Comment by Mathadon** [comment] 2017-02-13 18:20
@tatigabd the proposed fix is in #670 . Once that's merged can you check if that solves your error?

**Comment by tatigabd** [comment] 2017-02-14 10:36
Hi @Mathadon, thank you so much, it seems like the IDEAS package works now! The only syntax error is left: 
![image](https://cloud.githubusercontent.com/assets/25454871/22925553/7bcaca24-f2a9-11e6-932c-9d722727c4dc.png).

**Comment by Mathadon** [comment] 2017-02-14 16:31
That's odd. I'm not sure where that error comes from, also my OMEdit crashes when opening BESTEST.mo so I can't reproduce it. Let me fix that first.
In the meantime are you sure that you can't run a model yet? Since it's a 'warning' and I expect you can ignore it.

**Comment by tatigabd** [comment] 2017-02-15 11:08
@Mathadon I do launch the model despite this warning message, thank you so much, I think that issue could be closed. Best regards, Tatiana

**Comment by thorade** [comment] 2017-02-16 14:19
Using `constant Real MWh = 1/3600000000.0;` will make the warning disappear.

**Comment by damienpicard** [comment] 2017-02-22 09:53
This is solved in #670

**Closed by damienpicard** 2017-02-22 09:53 UTC

**Comment by thorade** [comment] 2017-03-17 08:04
I just happened to see that the OpenModelica documentation mentions large integers:
https://trac.openmodelica.org/OpenModelica/wiki/WritingCompliantLibraries#LargeIntegervalues
