### ISSUE TITLE
Radiator_NominalPower not found in the package.order file

### ISSUE THREAD

**Issue by Ja98** [open-ideas/IDEAS#775] opened 2018-03-02 15:31 UTC
I downloaded the IDEAs library and opened the library in OpenModelica but had the following errors: 

[3] 16:29:13 Grammar Error
[H:/Modelica/Modelica Libraries/IDEAS-master/IDEAS/Fluid/HeatExchangers/Examples/package.mo: 2:1-13:13]: Radiator_NominalPower was referenced in the package.order file, but was not found in package.mo, Radiator_NominalPower/package.mo or Radiator_NominalPower.mo.

[4] 16:29:13 Scripting Error
Failed to load package IDEAS () using MODELICAPATH H:\Modelica\Modelica Libraries\IDEAS-master\;C:/OpenModelica1.12.0-64bit/lib/omlibrary.

**Comment by Mathadon** [comment] 2018-03-02 15:36
This should now be fixed through b4c1e0e
Can you please verify?

**Comment by Ja98** [comment] 2018-03-05 07:56
It now fails with: 

[1] 08:52:57 Grammar Error
[H:/Modelica/Modelica Libraries/IDEAS-master/IDEAS/Fluid/Actuators/Valves/Examples/package.mo: 2:1-11:13]: ValveParameterization was referenced in the package.order file, but was not found in package.mo, ValveParameterization/package.mo or ValveParameterization.mo.

[2] 08:52:57 Scripting Error
Failed to load package IDEAS () using MODELICAPATH H:\Modelica\Modelica Libraries\IDEAS-master\;C:/OpenModelica1.12.0-64bit/lib/omlibrary.

**Comment by Mathadon** [comment] 2018-03-05 08:08
@Ja98 I'm afraid there may be more of these errors. The problem is that some models are in the `package.order` files, but they do not exist anymore as a `.mo` file. This can be fixed by removing those references from the `package.order` files. 
I do not have OpenModelica installed right now, but if you can fix these errors yourself and make a pull request I'd be happy to look into it. Otherwise it may take a few weeks/months before I find time to look into this since we need to develop a more structured approach for avoiding these issues to re-appear in the future.

**Comment by Ja98** [comment] 2018-03-05 08:14
Ok no problem. Thanks for looking in to it. If I get around to cleaning up the files I will let you know.

**Comment by Mathadon** [comment] 2018-03-13 14:40
@Ja98 this should be fixed now!

**Closed** 2018-03-13 14:39 UTC
