### ISSUE TITLE
Uccle.TMY file starts at wrong time

### ISSUE THREAD

**Issue by diederikverscheure** [open-ideas/IDEAS#1206] opened 2021-04-12 10:17 UTC
Hello,

is it possible that the Uccle.TMY file contains data copied from a standard TMY3 file?
According to this site TMY3 files start at 01/01 at local time 01:00:00.
https://build.openmodelica.org/Documentation/Buildings.BoundaryConditions.WeatherData.ReaderTMY3.html

In Uccle at 01/01 sunrise is around 8:45 and sunset is around 16:45.
We can check the global horizontal radiation values at time:
- 324000 s => HGloHor = 16 (in 1h timeslot preceding 9:00) => dubious because there was only 15 min of sun
- 57600 s => HGloHor = 1 (in 1h timeslot preceding 16:00)
- 61200 s => HGloHor = 0 (in 1h timeslot preceding 17:00) => not correct because sunset is at 16:44 so there should be radiation in preceding 1h timeslot.

Data copied from TMY3 should have two equal rows (at 0 s and 3600 s) and the last row should be dropped
see e.g. USA_CA_San.Francisco.Intl.AP.724940_TMY3.mos where this looks correct.

The problem that we have with this is that the solar altitude is > 0 (calculated), but the radiation values do not match with the solar altitude. 
Can anyone confirm this or anyone knows the origin of the file?

Thanks, 
Best regards,

Diederik

**Comment by Mathadon** [comment] 2021-04-12 11:01
@diederikverscheure thanks for reporting this. I'm looking into it but at first sight your analysis is correct.

**Comment by Mathadon** [comment] 2021-04-12 12:02
The commit ef8fc46b8 replaces

```
-Date (MM/DD/YYYY),Time (HH:MM),ETR (W/m^2),ETRN (W/m^2),GHI (W/m^2),GHI source,GHI uncert (%),DNI (W/m^2),DNI source,DNI uncert (%),DHI (W/m^2),DHI source,DHI uncert (%),GH illum (lx),GH illum source,Global illum uncert (%),DN illum (lx),DN illum source,DN illum uncert (%),DH illum (lx),DH illum source,DH illum uncert (%),Zenith lum (cd/m^2),Zenith lum source,Zenith lum uncert (%),TotCld (tenths),TotCld source,TotCld uncert (code),OpqCld (tenths),OpqCld source,OpqCld uncert (code),Dry-bulb (C),Dry-bulb source,Dry-bulb uncert (code),Dew-point (C),Dew-point source,Dew-point uncert (code),RHum (%),RHum source,RHum uncert (code),Pressure (mbar),Pressure source,Pressure uncert (code),Wdir (degrees),Wdir source,Wdir uncert (code),Wspd (m/s),Wspd source,Wspd uncert (code),Hvis (m),Hvis source,Hvis uncert (code),CeilHgt (m),CeilHgt source,CeilHgt uncert (code),Pwat (cm),Pwat source,Pwat uncert (code),AOD (unitless),AOD source,AOD uncert (code),Alb (unitless),Alb source,Alb uncert (code),Lprecip depth (mm),Lprecip quantity (hr),Lprecip source,Lprecip uncert (code)
-01/01/2005,07:00,0,0,0,3,0,0,3,0,0,3,0,0,3,0,0,3,0,0,3,0,-9990,0,0,10,E,8,9,E,8,9.8,E,8,5.4,E,8,74,E,8,999,E,8,276,E,8,1.8,E,8,-9990,0,0,-9990,0,0,1.358,E,8,0.209,E,8,0.26,E,8,-9990,-9990,0,0
-01/01/2005,08:00,0,0,0,3,0,0,3,0,0,3,0,0,3,0,0,3,0,0,3,0,-9990,0,0,10,E,8,9,E,8,9.8,E,8,5.1,E,8,73,E,8,999,E,8,237,E,8,2.4,E,8,-9990,0,0,-9990,0,0,1.327,E,8,0.209,E,8,0.26,E,8,-9990,-9990,0,0
-01/01/2005,09:00,2,95,0,3,10,0,3,20,0,3,10,16,3,10,5,3,20,16,3,10,-9990,0,0,10,E,8,9,E,8,9.8,E,8,5.5,E,8,75,E,8,999,E,8,259,E,8,2.2,E,8,-9990,0,0,-9990,0,0,1.362,E,8,0.209,E,8,0.26,E,8,-9990,-9990,0,0
-01/01/2005,10:00,111,1413,16,3,10,0,3,20,16,3,10,1896,3,10,0,3,20,1898,3,10,-9990,0,0,10,E,8,9,E,8,10.1,E,8,5.6,E,8,74,E,8,999,E,8,298,E,8,3.8,E,8,-9990,0,0,-9990,0,0,1.378,E,8,0.209,E,8,0.26,E,8,-9990,-9990,0,0
-01/01/2005,11:00,253,1413,43,3,10,0,3,20,43,3,10,4884,3,10,0,3,20,4895,3,10,-9990,0,0,10,E,8,9,E,8,10.5,E,8,4.7,E,8,67,E,8,999,E,8,230,E,8,3.1,E,8,-9990,0,0,-9990,0,0,1.289,E,8,0.209,E,8,0.26,E,8,-9990,-9990,0,0

```

by 

```
+25200  9.8     5.1     73      99927   0       0       318     0       0       0       0       0       0       9999    237     2.4     10      9       9999    99999   9       999999999       130     999     999     99      999     999     99
+28800  9.8     5.5     75      99927   26      1413    320     0       0       0       0       0       0       9999    259     2.2     10      9       9999    99999   9       999999999       140     999     999     99      999     999     99
+32400  10.1    5.6     74      99927   111     1413    321     16      0       16      19      0       19      9999    298     3.8     10      9       9999    99999   9       999999999       140     999     999     99      999     999     99
+36000  10.5    4.7     67      99927   253     1413    318     43      0       43      49      0       49      9999    230     3.1     10      9       9999    99999   9       999999999       130     999     999     99      999     999     99
+39600  10.9    4.8     66      99927   349     1413    318     65      0       65      74      0       74      9999    271     3.1     10      9       9999    99999   9       999999999       130     999     999     99      999     999     99

```

The solar irradiation data seems to be shifted by 1h since the value 43 W/m2 for the global horizontal irradiation that appears at time stamp '01/01/2005,11:00' is moved to time = 36000. This shift seems to be the cause of the problem. I'll look into how best to resolve this.

**Comment by diederikverscheure** [comment] 2021-04-14 08:24
According to this site in section  "Start and end data for annual weather data files"
https://build.openmodelica.org/Documentation/Buildings.BoundaryConditions.WeatherData.ReaderTMY3.html,
you could just duplicate the first line and remove the last line of the original file (time goes from 0, 3600, ...)

**Comment by Mathadon** [comment] 2021-04-15 12:17
@diederikverscheure that is indeed correct. The problem is that we're not sure whether the file has been altered in a different way where the time offset may be correct. Not shifting the data may then be wrong. We're looking into using a different reference weather file as an alternative option.

**Comment by Mathadon** [comment] 2021-04-16 16:11
@diederikverscheure we will create a new file, see #1209. Thanks for reporting. I'll close this issue.

**Closed by Mathadon** 2021-04-16 16:11 UTC
