### ISSUE TITLE
invalid argument when reading weather file

### ISSUE THREAD

**Issue by jagica** [open-ideas/IDEAS#1378] opened 2024-09-25 08:47 UTC
Hello
 
Here is my config : win 10 , Dymola 2021, Modelica 4.0
I am trying to get the example SimpleHouse to run. ( I am totally new to Modelica/Dymola and IDEAS....)
Please find the error log in the attached file.
Thanks for your help....

Jacques
[error file Dymola.txt](https://github.com/user-attachments/files/17128065/error.file.Dymola.txt)

**Comment by jelgerjansen** [comment] 2024-09-25 09:35
Hi Jacques,

It seems that Dymola is unable to open the weather file. Could you please check whether:

1. the `filNam` parameter of the `weaDat` component is equal to `Modelica.Utilities.Files.loadResource("modelica://IDEAS/Resources/weatherdata/USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.mos")`
2. you downloaded this .mos weather file when downloading IDEAS (check on your local computer, for you this is probably in the directory C:/Users/jacqu/Documents/Dymola/Library/IDEAS-3.0/IDEAS/Resources/weatherdata).

**Comment by jagica** [comment] 2024-09-25 10:32
1) yes it is, here is a paste of the filNam : Modelica.Utilities.Files.loadResource("modelica://IDEAS/Resources/weatherdata/USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.mos"
2) yes it is.
So what is wrong then ?

**Comment by jelgerjansen** [comment] 2024-09-25 10:54
Your `filNam` has no closing bracket ")". Did you forget to paste this, or is this wrong in your model? Because that might solve your issue. But if you didn't apply any changes to the original IDEAS model, the closing bracket should be there.

**Comment by jagica** [comment] 2024-09-25 11:13
I forgot to paste, here is the right paste
ModelicaServices.ExternalReferences.loadResource("modelica://IDEAS/Resources/weatherdata/USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.mos")

**Comment by jelgerjansen** [comment] 2024-09-25 11:27
Note that you use a different function, please use this one:
`Modelica.Utilities.Files.loadResource("modelica://IDEAS/Resources/weatherdata/USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.mos")`
Are you sure you didn't modify the model? If not, which IDEAS version did you download? I advise you to download our latest version.

Your error log indicates that Dymola tries to open "C:/Users/jacqu/Documents/Dymola/Library/IDEAS-3.0/IDEAS/modelica:/IDEAS/Resources/weatherdata/USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.mos", which refers to a wrong and non-existing folder on your computer. If the fix above does not solve your problem either, you might want to double check if the entire IDEAS library is loaded (in Dymola, go to "File>Open>Load...", and then click on the "package.mo" file that is located in the IDEAS directory).

**Comment by jagica** [comment] 2024-09-25 12:41
1)I used the function you recommended.

2)no I did not modify the model, as far as I know... The version of IDEAS I use is   3.0.0

3)yes the adress you report doesn't exist, the righ adress is : C:\Users\jacqu/Documents\Dymola\Library\IDEAS-3.0\IDEAS\modelica\IDEAS\Resources\weatherdata\
        a) is it because it uses / versus \ ?
        b) in the adress you report it includes a /modelica:/ which doesnt exist in my folder hirarchy. However it shows up in the 
            log report....strange ?? 
4)I open IDEAS by clicking on the package.mo that is located in the IDEAS folder.

**Comment by jelgerjansen** [comment] 2024-09-25 12:59
OK in that case I think the problem is your local directory structure.

The `modelica://` in `Modelica.Utilities.Files.loadResource("modelica://IDEAS/Resources/weatherdata/USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.mos")` refers to the libraries that are loaded in Dymola (those in the package browser).

Since your local directory structure also has "modelica" in there, Dymola might be confused here, hence the "modelica:/" in the error log file. Could you remove or rename this modelica folder and see if that solves the problem?

**Comment by jagica** [comment] 2024-09-25 13:35
I am not sure to understand, I have no modelica folder . it shows up only in the file structure as shown in Dymola.

**Comment by jelgerjansen** [comment] 2024-09-25 13:46
> 3)yes the adress you report doesn't exist, the righ adress is : C:\Users\jacqu/Documents\Dymola\Library\IDEAS-3.0\IDEAS\modelica\IDEAS\Resources\weatherdata

You said that the above address is the right one. Or where is the IDEAS folder located?

Furthermore, have you already tried to download the latest IDEAS version?

**Comment by jelgerjansen** [comment] 2024-09-25 14:16
The IDEAS v3.0 does not raise any errors on my computer, and we also never had this problem before.
Could you please send the IDEAS library that you use (as a zip file) to jelger.jansen@kuleuven.be? Then I'll have a look at your models and get back into contact via email or an online meeting to solve your issue.

Since I'm sure it's not an IDEAS bug, I'll close this issue.

**Closed by jelgerjansen** 2024-09-25 14:16 UTC
