### ISSUE TITLE
outerwall type orientation C PPD12 is internal wall

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#1177] opened 2020-10-28 09:06 UTC
Should be outer wall.

**Comment by Mathadon** [comment] 2020-10-28 14:00
`hFloor2` is not used

**Comment by jelgerjansen** [comment] 2023-04-03 10:14
@Mathadon can you direct to the models where this issue occurs? Is the issue still relevant or can it maybe be closed already?

**Comment by Mathadon** [comment] 2023-04-03 10:43
This is about the `Structure` model in `PPD12` but the title description does not make sense to me anymore. Perhaps I wrote it down wrong.. Can be closed as far as I am concerned.

**Comment by jelgerjansen** [comment] 2023-04-03 12:39
I did a quick check. The title is not clear about the zone where wall C is implemented wrong, but I checked them all and it looks fine.
Your second comment makes sense: a parameter was introduced for the height of the second floor, but this value is not used in the end (the height of the first floor is used for the second floor). @Mathadon since you made the model back in the days: do you prefer that I remove `hFloor2` and update the documentation of `hFloor1` or do I update the height of zones `bedroom2` and `bedroom3`? The values are very similar (2.7m vs 2.5m), so changing this will not lead to significant differences in results.

**Comment by Mathadon** [comment] 2023-04-03 14:09
better update the height to `hFloor2` :)

**Comment by jelgerjansen** [comment] 2024-03-25 10:39
The title appears to be correct after all... Face C of bedroom 2 was defined as an OuterWall, but used a construction type of the inner walls. I fixed this as well as the use of `hFloor2` for all rooms on the second floor. The new reference results look like this:
<img width="1893" alt="image" src="https://github.com/open-ideas/IDEAS/assets/43753266/bbfdd633-fd6b-4c84-8e55-00b950ad2529">

The sensor temperature for the porch and hallway are not affected and those of the living and dining room are hardly affected, which was to be expected because the applied changes relate to bedroom 2.
Gas use went from 359 MWh to 346 MWh, which makes sense (higher insulation of bedroom 2). This is also confirmed when plotting the heat emission of the radiator in bedroom 2 (less heat exchange for correct construction (red)):
<img width="1661" alt="image" src="https://github.com/open-ideas/IDEAS/assets/43753266/8e2212f1-0b80-4700-99e3-b2bea9401fa6">

@kldjonge in case you are using the PPD12 use case, you might want to update this as well.

**Comment by jelgerjansen** [comment] 2024-04-22 15:02
This issue is closed by PR #1354

**Closed by jelgerjansen** 2024-04-22 15:02 UTC
