### ISSUE TITLE
Problems at initialization

### ISSUE THREAD

**Issue by kldjonge** [open-ideas/IDEAS#1222] opened 2021-06-28 15:49 UTC
I encounter problems in initialization when trying to run certain models, the same error occurs in example models of IDEAS. (e.g. IDEAS.Buildings.Examples.ComfortExample). I use Dymola 2021 and MSL 3.2.3.

![image](https://user-images.githubusercontent.com/46526840/123665031-33936d00-d838-11eb-9d9b-ee40afe0e623.png)

**Comment by Mathadon** [comment] 2021-06-29 06:07
@kldjonge does the problem persist after a reboot? You’re not getting any error messages in the simulation tab?

**Comment by kldjonge** [comment] 2021-06-29 06:44
Yes it does, the problem also isn’t a problem anymore when I use an older version of IDEAS.

The actual simulation never starts. It crashes after translation but before time zero.

**Comment by kldjonge** [comment] 2021-06-29 06:49
I will ask some co-workers to test the same model to see if it stays persistant.

**Comment by Mathadon** [comment] 2021-06-29 06:52
Dymola 2020 works so in any case it seems an option to contact support :)

**Comment by kldjonge** [comment] 2021-06-29 08:50
I contacted them, they were able to reproduce the error. They are looking into it but told me that: "These errors are typically something wrong in external C code". 

Is there an external model that you changed but didn't push by any chance?

**Comment by Mathadon** [comment] 2021-06-29 08:55
The model that you referenced does not contain anything special that I can think of.. You could try to compile it without the Fanger model:


Maybe that provides a clue.

**Comment by kldjonge** [comment] 2021-06-30 07:51
This 56513a022c23c8b8a3f0d9645b5b739e34ae1a29, is where the error first occurs, so the error is probably in the weatherfile or the .mos format. That also explains why some models still work and others don't.

**Comment by Mathadon** [comment] 2021-06-30 11:53
Brussels.mos is missing a line for 3600s , which is not the case for Uccle.TMY. I'm not sure why this is the case. The file was auto-generated from the epw file. To be looked into further.

**Comment by jelgerjansen** [comment] 2021-09-15 14:18
@kldjonge do you still encounter this problem? I faced the same error today (when running `IDEAS.Examples.Tutorial.Example1` in Dymola 2022 after running the conversion script to make IDEAS compatible with MSL version 4.0.0). After removing some files in my working directory (more specifically dsin.txt, dslog.txt, buildlog.txt and dymosim.exe), I was able to run the example and the error didn't occur after this.

I still don't know why this error occurred (because there was no clear error message), but I think the weather file is not the problem.

**Comment by kldjonge** [comment] 2021-09-16 06:54
@jelgerjansen, yes I do. I just tried your trick and that didn't solve it either. 

Couldn't it be related to the file extension?
Because I'm avoiding the problem now by not using de Brussels.mos wheaterfile. The old .TMY files work fine for me.

**Comment by jelgerjansen** [comment] 2021-09-16 15:25
@kldjonge, I located the origin of the error. The weatherfile Brussels.mos contains a very long comment line (line 8, starting with '#COMMENTS 1, "IWEC- ...'). You can avoid the initialization error by removing this line from the weatherfile or by splitting it over multiple rows.

In the long term, @Mathadon will check if this error can be dealt with by adapting the C code called by the `SimInfoManager`.

**Comment by Mathadon** [comment] 2021-09-16 15:38
This seems to be a duplicate of https://github.com/ibpsa/modelica-ibpsa/issues/1432 

I.e. an update of IBPSA should solve this issue.

**Comment by Mathadon** [comment] 2021-09-17 11:31
@jelgerjansen @kldjonge this branch should solve your problem: 894_merged 
Can you verify?

**Comment by kldjonge** [comment] 2021-09-20 07:12
@Mathadon, works for me now.

**Comment by jelgerjansen** [comment] 2021-09-20 21:06
@Mathadon, also works for me now. I think we can close this issue.

**Closed** 2021-09-21 06:16 UTC
