### ISSUE TITLE
RadiatorHeating example fails in OpenModelica

### ISSUE THREAD

**Issue by BrendanSulliv** [open-ideas/IDEAS#1024] opened 2019-05-01 22:16 UTC
The RadiatorHeating model found under Templates.Examples does not flatten in OpenModelica due to a TranslationError caused by the replaceable heating model.

Here is the error code:
`[2] 18:11:00 Translation Error
[IDEAS.Templates.Examples.IdealRadiatorHeating: 3:68-4:43]: Trying to redeclare component heating but component not declared as replaceable.`

I tried to debug it and the heating model in IDEAS.Templates.Heating.RadiatorHeating  is declared replaceable so I'm not sure if the problem is on OpenModelica's end. Let me know what you think.

**Comment by Mathadon** [comment] 2019-05-02 08:00
@BrendanSulliv thanks for reporting this! I think the problem is that the two models extend a different base class and OpenModelica is more strict than Dymola at checking the base classes. This should be fixed once #1025 is merged.

**Closed** 2019-05-02 08:35 UTC
